# Keycloak — fournisseur d'identité OIDC (SSO Argo CD + Grafana).
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: hackathon
  source:
    repoURL: https://github.com/Hychion/Hackaton_-Equipe_13.git
    targetRevision: main
    path: apps/keycloak
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
