# Nos ClusterPolicies Kyverno (prévention de récidive), versionnées dans Git.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
spec:
  project: hackathon
  source:
    repoURL: https://github.com/Hychion/Hackaton_-Equipe_13.git
    targetRevision: main
    path: policies
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
