apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-web
  namespace: production
  labels:
    app: site-web
    tier: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site-web
  template:
    metadata:
      labels:
        app: site-web
    spec:
      automountServiceAccountToken: false
      containers:
        - name: web
          image: wordpress:6.4-apache
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 512Mi
          securityContext:
            privileged: false
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
